name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 
        
        **Note**: This project is in early development. We're focusing on core functionality first.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered

  - type: dropdown
    id: component
    attributes:
      label: Which component does this relate to?
      options:
        - User Portal
        - Shared Library
        - Admin Portal (future)
        - API/Backend integration
        - Build/Development tools
        - Documentation
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or mockups about the feature request here